categories:
- Materials science
- Muon spectroscopy
description: Generate MuSpinSim config from a structure file
homepage_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools
long_description: |
  Generate MuSpinSim config from a structure file
name: muspinsim_gen
owner: muon-spectroscopy-computational-project
remote_repository_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools/main/muspinsim_gen
