categories:
- Materials science
- Muon spectroscopy
description: Generate phonons
homepage_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools
long_description: |
  Given an input structure, generates a set of phonon configurations.
  Uses the pm-asephonons tool from pymuon-suite.
name: pm_asephonons
owner: elichad
remote_repository_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools/main/pm_asephonons
