categories:
- Materials science
- Muon spectroscopy
description: Cluster optimised structures
homepage_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools
long_description: |
  Given an input set of optimised muonated structures (UEP, CASTEP or DFTB+), performs clustering
  Uses the pm-muairss-read tool from pymuon-suite.
name: pm_muairss_read
owner: muon-spectroscopy-computational-project
remote_repository_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools/main/pm_muairss_read
