categories:
- Materials science
description: Convert a .cif file to a .cell file
homepage_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools
long_description: Convert a .cif file to a .cell file using cif2cell
name: cif2cell
owner: elichad
remote_repository_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools/main/cif2cell