categories:
- Materials science
- Muon spectroscopy
description: Optimise muonated structures
homepage_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools
long_description: |
  Given input muonated structures, optimise them with uep.
  Uses the pm-uep-opt tool from pymuon-suite.
name: pm_uep_opt
owner: muon-spectroscopy-computational-project
remote_repository_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools/main/pm_uep_opt
