categories:
- Materials science
- Muon spectroscopy
description: Run DFTB+ optimisation
homepage_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools
long_description: |
  Given input muonated structures, perform DFTB+ optimisation.
name: pm_dftb_opt
owner: muon-spectroscopy-computational-project
remote_repository_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools/main/pm_dftb_opt
