categories:
- Materials science
- Muon spectroscopy
description: Simulates Muon Spin Experiments
homepage_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools
long_description: |
  Given an input file, models spin dynamics of muon experiment.
name: muspinsim
owner: elichad
remote_repository_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools/main/muspinsim
