categories:
- Computational chemistry
- Molecular Dynamics
description: perform dftb+ optimisation (dftb+)
homepage_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools
long_description: |
  Given input muonated structures, perform dftb+ optimisation.
name: pm_dftb_uep_write
owner: muon-spectroscopy-computational-project
remote_repository_url: https://github.com/muon-spectroscopy-computational-project/muon-galaxy-tools/main/pm_muairss_write
